export const data = [
  [
    {
      name: 'sweet16',
      nativeLanguage: 'en-US',
      targetLanguageSynth: 'Google español de Estados Unidos',
      targetLanguageRecog: 'es-MX',
    },
    {
      targetLangText: 'él le da un regalo',
      pic: 'x.png',
      nativeLang: 'English',
      nativeLangText: 'he gives her a gift',
    },
    {
      targetLangText: 'ella dice mentiras',
      pic: 'dice.jpg',
      nativeLang: 'English',
      nativeLangText: 'she tells lies',
    },
    {
      targetLangText: 'ella es profesora',
      pic: 'x.png',
      nativeLang: 'English',
      nativeLangText: 'she is a teacher',
    },
    {
      targetLangText: 'él está enojado',
      pic: 'x.png',
      nativeLang: 'English',
      nativeLangText: 'he is mad',
    },
    {
      targetLangText: 'él hace la cena',
      pic: 'x.png',
      nativeLang: 'English',
      nativeLangText: 'he makes dinner',
    },
    {
      targetLangText: 'ella va a la playa',
      pic: 'x.png',
      nativeLang: 'English',
      nativeLangText: 'she goes to the beach',
    },
    {
      targetLangText: 'el perro mira la comida',
      pic: 'x.png',
      nativeLang: 'English',
      nativeLangText: 'the dog looks at the food',
    },
    {
      targetLangText: 'el gato oye el perro',
      pic: 'oye.png',
      nativeLang: 'English',
      nativeLangText: 'the cat hears the dog',
    },
    {
      targetLangText: 'él puede cantar',
      pic: 'x.png',
      nativeLang: 'English',
      nativeLangText: 'he can sing',
    },
    {
      targetLangText: 'el pone la llanta',
      pic: 'x.png',
      nativeLang: 'English',
      nativeLangText: 'he puts on the tire',
    },
    {
      targetLangText: 'el niño quiere chocolate',
      pic: 'x.png',
      nativeLang: 'English',
      nativeLangText: 'the boy wants chocolate',
    },
    {
      targetLangText: 'ella sabe hablar español',
      pic: 'x.png',
      nativeLang: 'English',
      nativeLangText: 'she knows how to speak Spanish',
    },
    {
      targetLangText: 'la niña sale',
      pic: 'x.png',
      nativeLang: 'English',
      nativeLangText: 'the girl leaves',
    },
    {
      targetLangText: 'él no tiene pelo',
      pic: 'x.png',
      nativeLang: 'English',
      nativeLangText: "he doesn't have hair",
    },
    {
      targetLangText: 'él le trae la comida',
      pic: 'x.png',
      nativeLang: 'English',
      nativeLangText: 'he brings her the food',
    },
    {
      targetLangText: 'ella viene a casa a las 8:00',
      pic: 'x.png',
      nativeLang: 'English',
      nativeLangText: 'she comes home at 8',
    },
  ],
  [
    {
      targetLanguage: 'Google español',
      name: 'sweet16Inf',
    },
    {
      targetLangText: 'dar',
      pic: 'da.jpg',
      nativeLang: 'English',
      nativeLangText: 'to give',
    },
    {
      targetLangText: 'decir',
      pic: 'dice.jpg',
      nativeLang: 'English',
      nativeLangText: 'to say',
    },
    {
      targetLangText: 'ser',
      pic: null,
      nativeLang: 'English',
      nativeLangText: 'to be',
    },
    {
      targetLangText: 'estar',
      pic: null,
      nativeLang: 'English',
      nativeLangText: 'to be',
    },
    {
      targetLangText: 'hacer',
      pic: 'hace.jpg',
      nativeLang: 'English',
      nativeLangText: 'to make, to do',
    },
    {
      targetLangText: 'ir',
      pic: 'va.jpg',
      nativeLang: 'English',
      nativeLangText: 'to go',
    },
    {
      targetLangText: 'mirar',
      pic: 'mira.jpg',
      nativeLang: 'English',
      nativeLangText: 'to look',
    },
    {
      targetLangText: 'oír',
      pic: 'oye.png',
      nativeLang: 'English',
      nativeLangText: 'to hear',
    },
    {
      targetLangText: 'poder',
      pic: 'puede.jpg',
      nativeLang: 'English',
      nativeLangText: 'to be able',
    },
    {
      targetLangText: 'poner',
      pic: 'pone.jpg',
      nativeLang: 'English',
      nativeLangText: 'to put',
    },
    {
      targetLangText: 'querer',
      pic: 'quiere.jpg',
      nativeLang: 'English',
      nativeLangText: 'to want',
    },
    {
      targetLangText: 'saber',
      pic: 'sabe.jpg',
      nativeLang: 'English',
      nativeLangText: 'to know',
    },
    {
      targetLangText: 'salir',
      pic: 'sale.jpg',
      nativeLang: 'English',
      nativeLangText: 'to leave',
    },
    {
      targetLangText: 'tener',
      pic: 'tiene.jpg',
      nativeLang: 'English',
      nativeLangText: 'to have',
    },
    {
      targetLangText: 'traer',
      pic: 'trae.jpg',
      nativeLang: 'English',
      nativeLangText: 'to bring',
    },
    {
      targetLangText: 'venir',
      pic: 'viene.jpg',
      nativeLang: 'English',
      nativeLangText: 'to come',
    },
  ],

  [
    {
      targetLanguage: 'Google español',
      name: 'top20Nouns',
    },
    {
      targetLangText: 'la vez',
      pic: '',
      nativeLang: 'English',
      nativeLangText: 'the time',
    },
    {
      targetLangText: 'el año',
      pic: '',
      nativeLang: 'English',
      nativeLangText: 'the year',
    },
    {
      targetLangText: 'el tiempo',
      pic: '',
      nativeLang: 'English',
      nativeLangText: 'the time',
    },
    {
      targetLangText: 'el día',
      pic: '',
      nativeLang: 'English',
      nativeLangText: 'the day',
    },
    {
      targetLangText: 'la cosa',
      pic: '',
      nativeLang: 'English',
      nativeLangText: 'the thing',
    },
    {
      targetLangText: 'el hombre',
      pic: '',
      nativeLang: 'English',
      nativeLangText: 'the man',
    },
    {
      targetLangText: 'la parte',
      pic: '',
      nativeLang: 'English',
      nativeLangText: 'the part',
    },
    {
      targetLangText: 'la vida',
      pic: '',
      nativeLang: 'English',
      nativeLangText: 'the life',
    },
    {
      targetLangText: 'el momento',
      pic: '',
      nativeLang: 'English',
      nativeLangText: 'the moment',
    },
    {
      targetLangText: 'la forma',
      pic: '',
      nativeLang: 'English',
      nativeLangText: 'the form',
    },
    {
      targetLangText: 'la casa',
      pic: '',
      nativeLang: 'English',
      nativeLangText: 'the house',
    },
    {
      targetLangText: 'el mundo',
      pic: '',
      nativeLang: 'English',
      nativeLangText: 'the world',
    },
    {
      targetLangText: 'la mujer',
      pic: '',
      nativeLang: 'English',
      nativeLangText: 'the woman',
    },
    {
      targetLangText: 'el país',
      pic: '',
      nativeLang: 'English',
      nativeLangText: 'the country',
    },
    {
      targetLangText: 'el lugar',
      pic: '',
      nativeLang: 'English',
      nativeLangText: 'the place',
    },
    {
      targetLangText: 'la persona',
      pic: '',
      nativeLang: 'English',
      nativeLangText: 'the person',
    },
    {
      targetLangText: 'la hora',
      pic: '',
      nativeLang: 'English',
      nativeLangText: 'the hour',
    },
    {
      targetLangText: 'el trabajo',
      pic: '',
      nativeLang: 'English',
      nativeLangText: 'the work',
    },
    {
      targetLangText: 'la mano',
      pic: '',
      nativeLang: 'English',
      nativeLangText: 'the hand',
    },
    {
      targetLangText: 'el fin',
      pic: '',
      nativeLang: 'English',
      nativeLangText: 'the end',
    },
    {
      targetLangText: 'el tipo',
      pic: '',
      nativeLang: 'English',
      nativeLangText: 'the type',
    },
    {
      targetLangText: 'la gente',
      pic: '',
      nativeLang: 'English',
      nativeLangText: 'the people',
    },
    {
      targetLangText: 'el ejemplo',
      pic: '',
      nativeLang: 'English',
      nativeLangText: 'the example',
    },
    {
      targetLangText: 'el lado',
      pic: '',
      nativeLang: 'English',
      nativeLangText: 'the side',
    },
    {
      targetLangText: 'el hijo',
      pic: '',
      nativeLang: 'English',
      nativeLangText: 'the son',
    },
    {
      targetLangText: 'el problema',
      pic: '',
      nativeLang: 'English',
      nativeLangText: 'the problem',
    },
    {
      targetLangText: 'la cuenta',
      pic: '',
      nativeLang: 'English',
      nativeLangText: 'the account',
    },
    {
      targetLangText: 'la palabra',
      pic: '',
      nativeLang: 'English',
      nativeLangText: 'the word',
    },
    {
      targetLangText: 'el niño',
      pic: '',
      nativeLang: 'English',
      nativeLangText: 'the boy',
    },
    {
      targetLangText: 'el padre',
      pic: '',
      nativeLang: 'English',
      nativeLangText: 'the father',
    },
  ],
];
